name: Build and Release .NET Desktop App

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore and Build solution
      run: |
        dotnet restore FusionCammy.sln
        dotnet build FusionCammy.sln -c Release

    - name: Zip All Output (exe + assets)
      run: |
        $buildOutput = Get-ChildItem -Path . -Recurse -Directory | Where-Object { $_.FullName -like '*\bin\Release\net8.0-windows*' }
        foreach ($folder in $buildOutput) {
          $zipPath = Join-Path $folder.Parent.Parent.FullName "FusionCammy.zip"
          Compress-Archive -Path "$($folder.FullName)\*" -DestinationPath $zipPath -Force
        }

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: |
          **/FusionCammy.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
